# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Z_Demo' do
  
   pod 'Componse_object',:path => 'Lib/Componse_object'
   pod 'Componse_login',:path => 'Lib/Componse_login'

end
